export const SET_LST_MOVIE = "SET_LST_MOVIE";
export const SET_COMING_MOVIE = "SET_COMING_MOVIE";
export const SET_SHOWING_MOVIE = "SET_SHOWING_MOVIE";
export const SET_INFO_MOVIE_UPDATE = "SET_INFO_MOVIE_UPDATE";
